### ISSUE TITLE
Practica-6_Irving

### ISSUE THREAD

**Issue by IrvingFernand0** [SistemasTecTlaxiaco/actividad-6-practica-de-proceso-de-negocio-con-web-30-equipo-de-irving#3]
[Reporte de Practica 6.pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-practica-de-proceso-de-negocio-con-web-30-equipo-de-irving/files/9630760/Reporte.de.Practica.6.pdf)

**Comment by magaly1311** [comment]
calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
